from collections import Counter
n=int(input())
room = tuple(map(int,input().split()))
print(Counter(room).most_common()[-1][0])

''' THIS QUESTION WAS DONE ON 08:03:2021
ON  10:36 AFTER STUDING THE BOOK ON DATA-STRUCTURE
AND ALGORITHMS'''
''' THANK YOU VERY MUCH LORD KRISHNA FOR THIS ALL
BEAUTIFUL AND AWESOME MATH, PHYSICS ,AND THIS
CS AND UNIVERSE ... I CANNOT DEFINE MY DEFINE MY
GRATITUDE IN WORD'S AND NOT WORD'S TO DEFINE
ABOUT YOU '''




