Regex_Pattern = r'(^[123][120][xs0][30Aa][xsu][.,])$'	# Do not delete 'r'.

import re

print(str(bool(re.search(Regex_Pattern, input()))).lower())
 ''' IN THIS QUESTION THE ABOVE STATEMENT WAS NOT
WORKING BCZ I HAVE NOT ADDED THE ^ SYMBOL IN STARTING
'''
 ''' THANK YOU MY BHAGWAN FOR THIS BEAUTIFUL UNIVERSE
'''  ''' AND YESTERDAY NASA'S ROVER LANDED ON MARS
AND THIS MISSION WAS LEAD BY AN INDIAN LADY SCIENTIST
AND SHE GOT VIRAL BECAUSE OF ITS BINDI '''
 # THANK YOU SO MUCH BHAGWAN
 
